version: '3'
services:
  db:
    image: postgres
    container_name: oak-bike-db
    ports:
      - "5432:5432"
    expose:
      - "5432"
  oak-bike:
    build:
      context: .
      dockerfile: ./docker/Docker.server/Dockerfile
    image: oak-bike
    env_file: .env
    container_name: oak-bike
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db:postgres
