export const SET_REPORT_STATUS = "SET_REPORT_STATUS";
export const SET_REPORT_IMAGE = "SET_REPORT_IMAGE";
export const SET_REPORT_COORDS = "SET_REPORT_COORDS";

export const GET_USER_LOCATION = "GET_USER_LOCATION";
export const HANDLE_IMAGE_UPLOAD = "HANDLE_IMAGE_UPLOAD";
export const HANDLE_REPORT_UPLOAD = "HANDLE_REPORT_UPLOAD";
