# Generated by Django 2.1 on 2019-07-11 00:15

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('img_url', models.CharField(blank=True, max_length=256)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, max_length=256)),
                ('report_type', models.CharField(blank=True, choices=[('H', 'Pothole'), ('P', 'Parking'), ('O', 'Other')], max_length=1)),
            ],
        ),
    ]
