# Generated by Django 2.1 on 2019-07-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oakbike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
