# Generated by Django 2.1 on 2019-07-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oakbike', '0002_auto_20190320_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='contact',
        ),
        migrations.AddField(
            model_name='report',
            name='type_incident',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='img_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
